sudo: required
dist: trusty
language: node_js
node_js:
- node
before_script:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: V2vsnXq/XPJYQPCp34967paJBk1tKxFV/zldxSq0EC8pH5A8VMc6ZanMMSXeDlTOSYcBA1YhIewxrJ4W9hgL73t9McGowP1OxaZg54h0haOvRYY/90KmgvEvxRpTDeWYk4hZofSFdqEYU5kiGyVrahCvxk1D1/UnZZ6Ixe/B3faNYkYQRD/NINs+mwSp/m/wAcnk82lGoxuoud+GJ+aqO3UwcwlLfMNIsX06Q713o1QkPEP6GjYYHEKL0xdNyIULsUZK4ipldSZtKwdbZhlOmGXhz1+K2/0ORX1IrjZlXZ1Q/vm8VQ9Wx29A7hraWNkD6lVoZ11g0oiMEdBjT4LiqsnMBCMyT+tpBcEgBc5Pba7QJ+arD3mpFz1asbjsY562z5zswVNUnX8WDFe0dKOeimCc0nCJcIz/YbBvJmxlpY6grJCIftA/FKkxZ6RtGTAOrjlOhTXpZEHv3989uruST6AyE6mB7bT71loG+C2Xs0Kp9HDcm7z5R5AmzR9uYSz+O2yppR3eV9QWqnMz2jX8/YGe5OpngBoZLXuwNXkCfpkYAJnTxhbppSsIQlvt7YxCVuqXIwopSYGZFEXkVkuf7T9zA+hAUbn3zR0T9ArPSBxZfEPSM7hwSIurkm4QkcT9ntxuloRCBuxmi4ZQS54QmlnElUYdDFeKcBuaH2sEP+s=
  app: Github-Ranker
  on:
    repo: dolan-bio/Github-Ranker
